apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: bfh
spec:
  host: bfh.puzzle.ch
  port:
    targetPort: 5000
  to:
    kind: Service
    name: simple-example
    weight: 100
  wildcardPolicy: None
